### PR TITLE
Fixing erc20-counter example compilation

### PR DESCRIPTION
**Pull request by carlosgj94**
Hey, while trying to make some changes to the example I realised there's a type missing in the solidity ABI inside the publisher. 
Very small and isolated.

Please, let me know if there's some code guidelines I should be following that I missed. Or just fix it yourselves, it's a very quick thing :)

### CODE REVIEW

**Comment by nategraf** [comment]
Hey @carlosgj94, thanks for submitting this fix! It looks like I messed this up with a couple of my recent PRs, and missed it because the CI on the examples has been broken for unrelated reasons. https://github.com/risc0/risc0-ethereum/pull/105

This looks great! Is it still draft, or should we go ahead and mark it ready for review?

**Comment by nategraf** [comment]
@carlosgj94 we've rolled this change into https://github.com/risc0/risc0-ethereum/pull/109, which is merged now. I tried to add you as a co-author, but it looks like GitHub didn't accept my syntax 😅. Anyway! I believe this fixes the issue and let me know if you have any others.

**Comment by austinabell** [comment]
> @carlosgj94 we've rolled this change into #109, which is merged now. I tried to add you as a co-author, but it looks like GitHub didn't accept my syntax 😅. Anyway! I believe this fixes the issue and let me know if you have any others.

Assume meant to link https://github.com/risc0/risc0-ethereum/pull/93

**Comment by carlosgj94** [comment]
That's totally, fine, no worries :) My goal was just getting it fixed so I can build on your stack myself hahah
Thanks for the fix!

**Pull request closed without merging**
