### PR TITLE
WEB3-94: Updated deployment scripts and guide from 1.1 deployment

### PR DESCRIPTION
**Pull request by nategraf**
During the 1.1 deployment, I implemented a number of improvements to the deployment process to make it a bit easier and less error prone.
Primary among these changes is adding a `deployment.toml` file that records the addresses of and associated information about each chain we deploy to, and the contracts that are deployed there.
My hope is to use this file to do additional work around further automating deployment, testing that deployments are correctly configured on-chain, and generating the table of addresses that goes into our docs.

### CODE REVIEW

**Comment by nategraf** [comment]
This PR is marked as draft, as I'd like to merge the `deployment_guide.md` file into the existing `README`. They are currently two files simply due to the process by which I ended up writing that file.

**Comment by nategraf** [comment]
@capossele, this is ready for review. Give it a look when you have a chance. I'm hoping you'll be able to run this for the 1.2 release, when it happens. (You can ask me for the `deployment_secrets.toml` file and other secrets you'll need)

**Review by capossele — APPROVED** [review]
Only 600 lines of instruction 🙈

**Comment by nategraf** [comment]
> Only 600 lines of instruction 🙈

And believe me when I say it's an easier process now! 😅

**Pull request merged**
